### ISSUE TITLE
license

### ISSUE THREAD

**Issue by luke4u** [nikolamilosevic86/TableInformationExtractionScripts#1]
Hi there,

Thanks for open source this great job! Can you please provide clarity on the license of your project? 

Thanks. 
Luke

**Comment by rashibudati** [comment]
Hi @nikolamilosevic86 ,
Can you please provide instructions as to how to set up this project? @luke4u, were you able to set up this project? if yes, can you please provide steps ?
Thanks!

**Comment by nikolamilosevic86** [comment]
The license is GNU GPL v3.

@rashibudati the following guide should help https://github.com/nikolamilosevic86/TabInOut/wiki/2.-TabInOut-(TableInOut)-User-Guide
